#ifndef PINOUT_H_INCLUDED
#define PINOUT_H_INCLUDED

// MAIN System
#define LED_ON GPIOA->BSRR|=GPIO_BSRR_BS15     //PA15
#define LED_OFF GPIOA->BSRR|=GPIO_BSRR_BR15    //PA15

// UART
/*
PB6 - TX
PB7 - RX
*/

// SPI Comm
/*
PB3 - SPI_CLK
PB5 - SPI_MOSI
*/
#define DATA_RDY_ON GPIOB->BSRR|=GPIO_BSRR_BS4 //PB4
#define DATA_RDY_OFF GPIOB->BSRR|=GPIO_BSRR_BR4 //PB4

// Shift registers
#define SHIFT_DATA_ON GPIOA->BSRR|=GPIO_BSRR_BS6     //PA6
#define SHIFT_DATA_OFF GPIOA->BSRR|=GPIO_BSRR_BR6    //PA6
#define SHIFT_CLK_ON GPIOB->BSRR|=GPIO_BSRR_BS2     //PB2
#define SHIFT_CLK_OFF GPIOB->BSRR|=GPIO_BSRR_BR2    //PB2
#define SHIFT_LE1_ON GPIOB->BSRR|=GPIO_BSRR_BS0     //PB0
#define SHIFT_LE1_OFF GPIOB->BSRR|=GPIO_BSRR_BR0    //PB0
#define SHIFT_LE2_ON GPIOB->BSRR|=GPIO_BSRR_BS1     //PB1
#define SHIFT_LE2_OFF GPIOB->BSRR|=GPIO_BSRR_BR1    //PB1
#define PLL1_MISO (GPIOA->IDR & GPIO_IDR_ID7)      //PA7
#define PLL2_MISO (GPIOB->IDR & GPIO_IDR_ID10)      //PB10

// PLL 1-1 - LMX2491
// GND
// +5V
#define R_MOD_HIGH GPIOB->BSRR|=GPIO_BSRR_BS11     //PB11
#define R_MOD_LOW GPIOB->BSRR|=GPIO_BSRR_BR11     //PB11
#define R_CLK_HIGH GPIOB->BSRR|=GPIO_BSRR_BS13    //PB13
#define R_CLK_LOW GPIOB->BSRR|=GPIO_BSRR_BR13     //PB13
#define R_DATA_HIGH GPIOB->BSRR|=GPIO_BSRR_BS15   //PB15
#define R_DATA_LOW GPIOB->BSRR|=GPIO_BSRR_BR15    //PB15
#define R_LE_HIGH GPIOA->BSRR|=GPIO_BSRR_BS8      //PA8
#define R_LE_LOW GPIOA->BSRR|=GPIO_BSRR_BR8       //PA8
#define R_MUX (GPIOB->IDR & GPIO_IDR_ID14)        //PB14
#define R_TRIG1_HIGH GPIOB->BSRR|=GPIO_BSRR_BS12  //PB12
#define R_TRIG1_LOW GPIOB->BSRR|=GPIO_BSRR_BR12   //PB12

// PLL 1-2 - STuW81300
//+5V
//GND
#define LE_HIGH GPIOA->BSRR|=GPIO_BSRR_BS9      //PA9
#define LE_LOW GPIOA->BSRR|=GPIO_BSRR_BR9       //PA9
#define CLK_HIGH GPIOA->BSRR|=GPIO_BSRR_BS10    //PA10
#define CLK_LOW GPIOA->BSRR|=GPIO_BSRR_BR10     //PA10
#define DATA_HIGH GPIOA->BSRR|=GPIO_BSRR_BS11   //PA11
#define DATA_LOW GPIOA->BSRR|=GPIO_BSRR_BR11    //PA11
#define MUX (GPIOA->IDR & GPIO_IDR_ID12)        //PA12

#endif /* PINOUT_H_INCLUDED */
